= SBim
:author: Marcos Cruz (programandala.net)
:revdate: 2016-12-09

// This file is part of SBim
// http://programandala.net/es.programa.sbim.html

// This file is written in AsciiDoc/Asciidoctor format
// (http://asciidoctor.org)

// You may do whatever you want with this work, so long as you
// retain the copyright/authorship/acknowledgment/credit
// notice(s) and this license in all redistributed copies and
// derived works.  There is no warranty.

SBim is a preprocessor for S*BASIC (QL SuperBASIC and SMSQ SBASIC).
SBim is written in VimL, the programming language of the Vim editor.

Mode details (at the moment, only in Spanish):
http://programandala.net/es.programa.sbim.html

== Install

. Edit CONFIG.sh to suit your installation directory and the way files
  should be installed. Uncomment only the desired options. Defaults:
  user-wide installation with symbolic links.
. Execute `INSTALL.sh`.

==  Uninstall

. Execute `UNINSTALL.sh`.

== Files

CONFIG.sh             :: the install options, to be edited
INSTALL.sh            :: the installer
README.adoc           :: this file
UNINSTALL.sh          :: the uninstaller
sbasic2sbim.vim       :: a simple converter from S*BASIC to SBim
sbim.converter.vim    :: the converter from SBim to actual S*BASIC
sbim.ftdetect.vim     :: the Vim filetype detecter for SBim
sbim.ftplugin.vim     :: the Vim filetype plugin for SBim
sbim.syntax.vim       :: the Vim syntax file for SBim
superbasic.syntax.vim :: the Vim syntax file for SuperBASIC

Note: `sbasic2sbim.vim` is not installed by `INSTALL.sh`. It must be
used manually from Vim. See the source for details.

== Git repository

The Git repository was created on 2016-12-09 from development backups,
in order to prepare the first release and make future development
easier.
