= SBim
:author: Marcos Cruz (programandala.net)
:revdate: 2017-09-28

// This file is part of SBim
// http://programandala.net/es.programa.sbim.html

// This file is written in AsciiDoc/Asciidoctor format
// (http://asciidoctor.org)

// You may do whatever you want with this work, so long as you
// retain the copyright/authorship/acknowledgment/credit
// notice(s) and this license in all redistributed copies and
// derived works.  There is no warranty.

SBim is an S*BASIC preprocessor  written in Vimscript, the
programming language of the http://www.vim.org[Vim editor].

"S*BASIC" means
http://superbasic-manual.readthedocs.io/en/latest/[SuperBASIC and its improved descendant SBASIC].

Project home page: http://programandala.net/en.program.sbim.html

== Files

LICENSE.txt           :: the license
Makefile              :: used by `make` to (un)install SBim
README.adoc           :: this file
VERSIONS.adoc         :: the versions history
sbasic2sbim.vim       :: a simple converter from S*BASIC to SBim
sbim.converter.vim    :: the converter from SBim to actual S*BASIC
sbim.ftdetect.vim     :: the Vim filetype detecter for SBim
sbim.ftplugin.vim     :: the Vim filetype plugin for SBim
syntax/sbim.vim       :: the Vim syntax file for SBim
syntax/superbasic.vim :: the Vim syntax file for SuperBASIC

Note: `sbasic2sbim.vim` is not installed. It must be used manually
from Vim. See the source for details.

== Install and uninstall

----
make install
make uninstall
----

The Vim files are installed in <\~/.vim>.
The CLI command is installed in <\~/bin>.

== Git repository

The Git repository was created on 2016-12-09 from development backups,
in order to prepare the first release and make future development
easier.
